apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: myapp1
  labels:
    app: myapp1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp1

  template:
    metadata:
      labels:
        app: myapp1
        tier: myapp1
    spec:
      containers:
        - name: myapp1
          image: premkumarmkr/todo_app:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
              name: myapp1

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: myapp1
  labelsy
    app: myapp1
spec:
  selector:
    app: myapp1
    tier: myapp1
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 5000 # The port exposed by the service
  type: LoadBalancer # type of the service.
